#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit, this file will also be sourced.

DEVICE="default"
USE_XRDB=true

if [ "$USE_XRDB" = true ]; then
    xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
fi

case "$DEVICE" in
    "cz desktop")
        xrandr --dpi 180 &
        sh ./.screenlayout/currentbutslower.sh &
        autostart="picom dunst unclutter remaps settokyo protonmail-bridge synology-drive"
        redshift -P -O 3300 &
        rivalcfg -s 1100 -S 1300 &
        xwallpaper --zoom "/home/carbon/.local/share/bg" &
        ;;
    "cz x220")
        xrandr --dpi 100 &
        setbg ~/sdrive/pictures/wallpapers/x220/0.png &
        autostart="mpd picom dunst unclutter remaps settokyo synology-drive"
        redshift -P -O 3300 &
        # enable natural scrolling on touchpad & decrease sensitivity of trackpoint
        tp_id=$(xinput list --id-only "TPPS/2 IBM TrackPoint")
        tpad_id=$(xinput list --id-only "SynPS/2 Synaptics TouchPad")
        [ -n "$tp_id" ] && xinput --set-prop "$tp_id" "libinput Accel Speed" -0.5 &
        [ -n "$tpad_id" ] && xinput --set-prop "$tpad_id" "libinput Natural Scrolling Enabled" 1 &
        ;;
    "default" | *)
        # Set DPI. User may want to use a larger number for larger screens.
        xrandr --dpi 96
        setbg &
        autostart="mpd picom dunst unclutter remapd"
        ;;
esac

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

if command -v ya > /dev/null
then
    git clone https://github.com/BennyOe/tokyo-night.yazi.git ~/.config/yazi/flavors/tokyo-night.yazi
    ya pkg add yazi-rs/plugins:git
    ya pkg add yazi-rs/plugins:smart-enter
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
if [ "$USE_XRDB" = true ]; then
    [ -n "$xrdbpid" ] && wait "$xrdbpid"
fi
