#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit, this file will also be sourced.

xrandr --dpi 200 & # Set DPI. User may want to use a larger number for larger screens.
sh ./.screenlayout/currentbutslower.sh &
#setbg &			# set the background with the `setbg` script
#bgpicker.py &
#setbg_bee &

#settokyo &
#protonmail-bridge &
#synology-drive &

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

#autostart="mpd picom dunst unclutter pipewire wireplumber synology-drive remaps"
autostart="mpd picom dunst unclutter remaps settokyo protonmail-bridge synology-drive"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

redshift -P -O 3300 &
rivalcfg -s 1100 -S 1300 &

if command -v ya > /dev/null
then
    git clone https://github.com/BennyOe/tokyo-night.yazi.git ~/.config/yazi/flavors/tokyo-night.yazi
    ya pack -a yazi-rs/plugins:git
    ya pack -a yazi-rs/plugins:smart-enter
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
