#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit, this file will also be sourced.

DEVICE="default"
USE_XRDB=true

if [ "$USE_XRDB" = true ]; then
    xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
fi

case "$DEVICE" in
    "cz desktop")
        xrandr --dpi 200 &
        sh ./.screenlayout/currentbutslower.sh &
        autostart="mpd picom dunst unclutter remaps settokyo protonmail-bridge synology-drive"
        redshift -P -O 3300 &
        rivalcfg -s 1100 -S 1300 &
        ;;
    "cz laptop")
        xrandr --dpi 100 &
        setbg ~/sdrive/pictures/wallpapers/x220/0.png &
        autostart="mpd picom dunst unclutter remaps settokyo synology-drive"
        redshift -P -O 3300 &
        # i think these are broken:
        xinput --set-prop 11 325 -0.5 & # slow down trackpoint
        xinput --set-prop 13 325 -0.5 & # slow down usb mouse
        xinput --set-prop 10 313 1 &    # natural scrolling touchpad
        ;;
    "default" | *)
        # Set DPI. User may want to use a larger number for larger screens.
        xrandr --dpi 96
        setbg &
        autostart="mpd picom dunst unclutter remapd"
        ;;
esac

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

if command -v ya > /dev/null
then
    git clone https://github.com/BennyOe/tokyo-night.yazi.git ~/.config/yazi/flavors/tokyo-night.yazi
    ya pack -a yazi-rs/plugins:git
    ya pack -a yazi-rs/plugins:smart-enter
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
if [ "$USE_XRDB" = true ]; then
    [ -n "$xrdbpid" ] && wait "$xrdbpid"
fi
