# from: https://yazi-rs.github.io/docs/tips
[[manager.prepend_keymap]]
on = "<C-n>"
run = '''
    shell 'dragon-drop --and-exit --on-top "$@"' --confirm
'''
desc = "Open the drag and drop utility"

[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell in the current directory"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = 'cd ~/Downloads'
desc = "Open ~/Downloads"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = 'cd ~/Documents'
desc = "Open ~/Documents"

[[manager.prepend_keymap]]
on = "l"
run = 'plugin smart-enter'
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["g", "t"]
# on = "T"
when = '[[selected]] is_directory'
run = '''
    shell 'picard "$@"' --confirm
'''
desc = "Open Picard with the selected directory"

[[manager.prepend_keymap]]
on = ["g", "s"]
when = '[[selected]] is_directory'
run = '''
    shell 'scrobble "$0"' --confirm --orphan
'''
desc = "Scrobble directory to last.fm"

[[manager.prepend_keymap]]
on = ["g", "b"]
run = '''
    shell 'setbg "$0"' --confirm --orphan
'''
desc = "Run setbg script on file."

[[manager.prepend_keymap]]
on = ["g", "B"]
when = '[[selected]] is_directory'
run = '''
    shell 'baobab "$0"' --confirm
'''
desc = "Run baobab on directory."
